AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Type: String
    Description: Name of the bucket
    Default: "xplore-web"
  Environment:
    Type: String
    Description: Environment to deploy stack
    Default: dev

Resources:
  S3CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              Fn::ImportValue:
                !Sub "BucketDomainName-${Environment}"
            Id: S3CloudFront
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: S3CloudFront
          SmoothStreaming: 'false'
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
        CustomErrorResponses:
        - ErrorCode: 404
          ResponsePagePath: '/index.html'
          ResponseCode: 200
        - ErrorCode: 403
          ResponsePagePath: '/index.html'
          ResponseCode: 200
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: PublicRead
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${BucketName}-${AWS::AccountId}-${Environment}/*'
      Bucket: !Sub ${BucketName}-${AWS::AccountId}-${Environment}